
#ifndef REGOLITH_GLOBAL_VERSION_H_
#define REGOLITH_GLOBAL_VERSION_H_


//#define REGOLITH_VERSION_DEBUG
#define REGOLITH_VERSION_RELEASE


#define REGOLITH_VERSION_MAJOR "A"
#define REGOLITH_VERSION_MINOR "3"
#define REGOLITH_VERSION_PATCH "5"

#define REGOLITH_VERSION_NUMBER REGOLITH_VERSION_MAJOR "." REGOLITH_VERSION_MINOR "-" REGOLITH_VERSION_PATCH


#endif // REGOLITH_GLOBAL_VERSION_H_

