
#ifndef REGOLITH_GLOBAL_VERSION_H_
#define REGOLITH_GLOBAL_VERSION_H_

#define REGOLITH_VERSION_MAJOR "0"
#define REGOLITH_VERSION_MINOR "1"
#define REGOLITH_VERSION_PATCH "0"

#define REGOLITH_VERSION_NUMBER REGOLITH_VERSION_MAJOR "." REGOLITH_VERSION_MINOR "-" REGOLITH_VERSION_PATCH


#endif // REGOLITH_GLOBAL_VERSION_H_

