
#ifndef __REGOLITH__DEFINITIONS_H__
#define __REGOLITH__DEFINITIONS_H__


#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_ttf.h>


#define REGOLITH_VERSION_NUMBER "0.1"


namespace Regolith
{

  const float pi = 3.14159265358979323846;

  const float e = 2.7182818284590452353602874;

  const float epsilon = 1.0E-6;


  enum ObjectProperty
  {
    OBJECT_SIMPLE = 0,
    OBJECT_ANIMATED = 1 << 0,
    OBJECT_HAS_COLLISION = 1 << 1,
    OBJECT_HAS_INPUT = 1 << 2
  };


  enum ObjectTeam
  {
    TEAM_ENVIRONMENT,
    TEAM_PLAYER,
    TEAM_NONPLAYER,
    TEAM_ENEMY,
    TEAM_TOTAL
  };


  enum GameEvent
  {
    REGOLITH_SCENE_END,
    REGOLITH_FULLSCREEN,
    REGOLITH_EVENT_TOTAL
  };


  enum CharacterState
  {
    CHARACTER_REST,
    CHARACTER_CREATION,
    CHARACTER_DESTRUCTION,
    CHARACTER_RUNNING,
    CHARACTER_CROUCHING,
    CHARACTER_CRAWLING,
    CHARACTER_LOOKING_UP,
    CHARACTER_LOOKING_DOWN,
    CHARACTER_JUMPING,
    CHARACTER_LANDING,
    CHARACTER_HARD_LANDING,
    CHARACTER_FALLING,
    CHARACTER_DAMAGE,
    CHARACTER_TOTAL
  };

}

#endif // __REGOLITH__DEFINITIONS_H__

